pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/HARISH07-1/cloudops-enterprise-platform.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Build stage completed'
            }
        }

        stage('Docker Build') {
            steps {
                bat 'docker build -t cloudops-html-app -f docker/Dockerfile .'
            }
        }

        stage('Deploy Container') {
            steps {
                script {
                    // Stop container if running (ignore failure)
                    bat(returnStatus: true, script: 'docker stop cloudops-container')

                    // Remove container if exists (ignore failure)
                    bat(returnStatus: true, script: 'docker rm cloudops-container')

                    // Run new container (this MUST succeed)
                    bat 'docker run -d -p 8081:80 --name cloudops-container cloudops-html-app'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
